routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::group([
    'middleware' => ['auth', 'can:use-site'],
], function () {

/**
 * HOME &EVENT
 */
Route::get('/', 'HomeController@index')->name('home');
Route::get('/candidates', 'Candidate\CandidateController@getListMatch');
Route::get('/candidates-for-interview', 'Candidate\CandidateController@getCandidatesForInterview');
    Route::get('candidate/stat','Candidate\CandidateController@stat')->name('candidate.stat');

Route::resource('candidate', 'Candidate\CandidateController');
Route::group([
        'prefix' => 'candidate',
        'as' => 'candidate.',
        'namespace' => 'Candidate',
    ],
    function () {

        Route::post('change-status/{candidate}/{status}', 'CandidateController@changeStatus')->name('changeStatus');
        Route::get('create-candidate-record/{user}', 'CandidateController@createCandidateRecord')->name('createCandidateRecord');
        Route::post('store-candidate-record/{user}', 'CandidateController@storeCandidateRecord')->name('storeCandidateRecord');
        Route::get('get', 'CandidateController@getList');
        Route::get('candidates', 'CandidateController@getListMatch');
    }
);

Route::resource('user', 'User\UserController');
Route::group([
    'prefix' => 'user',
    'as' => 'user.',
    'namespace' => 'User',
],
    function () {
        Route::post('change-status/{user}/{status}', 'UserController@changeStatus')->name('changeStatus');
    }
);

Route::resource('vacancy', 'VacancyController');

Route::group([
    'prefix' => 'data',
    'as' => 'data.',
    'namespace' => 'Data',
],
    function () {
        Route::resource('currency', 'CurrencyController');
        Route::resource('city', 'CityController');
        Route::resource('position', 'PositionController');
        Route::resource('company', 'CompanyController');
        Route::resource('remote-access', 'RemoteAccessController');
    }
);

/**
 * INTERVIEWS
 */
Route::resource('interview', 'InterviewController');
Route::get('interview/candidates/all', 'InterviewController@getCandidates')->name('interview.candidates.getAll');


/**
 * EVENTS & CALENDAR
 */
Route::any('calendar', 'Event\EventController@index')->name('calendar.index');
Route::any('calendar/create', 'Event\EventController@create')->name('calendar.create');
Route::any('calendar/add', 'Event\EventController@add')->name('calendar.add');

});



/**
 * USERS
 */

app/Http/Controllers/VacancyController.php
<?php

namespace App\Http\Controllers;

use App\Entities\Data\DataDTO;
use App\Entities\Vacancy;
use App\Http\Requests\Vacancy\CreateRequest;
use App\Http\Requests\Vacancy\UpdateRequest;
use App\Services\Vacancy\VacancyService;
use Illuminate\Contracts\View\View;
use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * Class VacancyController
 */
class VacancyController extends Controller
{
    /**
     * @var VacancyService
     */
    private $service;

    /**
     * VacancyController constructor.
     * @param VacancyService $service
     */
    public function __construct(VacancyService $service)
    {
        $this->service = $service;
        $this->middleware('can:manage-vacancies')->except(['index', 'show']);
    }

    /**
     * @return View
     */
    public function index(): View
    {
        $vacancies = Vacancy::orderBy('updated_at')->with('city')->paginate(10);
        return view('vacancy.index', compact('vacancies'));
    }

    /**
     * @return View
     */
    public function create(): View
    {
        $data = new DataDTO();
        return view('vacancy.create', compact('data'));
    }

    /**
     * @param CreateRequest $request
     * @return RedirectResponse
     */
    public function store(CreateRequest $request): RedirectResponse
    {
        try {
            $this->service->createVacancy($request);
        } catch (\Exception $e) {
            return back()->with('error', $e->getMessage());
        }

        return redirect()->route('vacancy.index');
    }

    /**
     * @param Vacancy $vacancy
     * @return View
     */
    public function edit(Vacancy $vacancy): View
    {
        $data = new DataDTO();
        return view('vacancy.edit', compact('vacancy', 'data'));
    }

    /**
     * @param UpdateRequest $request
     * @param Vacancy $vacancy
     * @return RedirectResponse
     */
    public function update(UpdateRequest $request, Vacancy $vacancy): RedirectResponse
    {
        /*$vacancy = Vacancy::find()->where(['id' => $id])->one();
        $vacancy->name=$request->name();*/


        try {
            $this->service->updateVacancy($request, $vacancy);
        } catch (\Exception $e) {
            return back()->with('error', $e->getMessage());
        }

        return redirect()->route('vacancy.show', $vacancy);
    }

    /**
     * @param Vacancy $vacancy
     * @return View
     */
    public function show(Vacancy $vacancy): View
    {
        return view('vacancy.show', compact('vacancy'));
    }

    /**
     * @param Vacancy $vacancy
     * @return RedirectResponse
     */
    public function destroy(Vacancy $vacancy): RedirectResponse
    {
        try {
            $this->service->deleteVacancy($vacancy);
        } catch (\Exception $e) {
            return back()->with('error', $e->getMessage());
        }
        return redirect()->route('vacancy.index');
    }
}

resources/views/vacancy/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    Создание новой вакансии
                    <a href="{{ route('vacancy.index') }}" class="close">
                        <span aria-hidden="true">&times;</span>
                    </a>
                </div>

                <div class="card-body">
                    <form method="POST" action="{{ route('vacancy.store') }}">
                        @csrf

                        <div class="form-group">
                            <label for="title" class="col-form-label required">Заголовок</label>
                            <input id="title" class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}" name="title" value="{{ old('title') }}" required>
                            @if ($errors->has('title'))
                                <span class="invalid-feedback"><strong>{{ $errors->first('title') }}</strong></span>
                            @endif
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="salary" class="col-form-label">Зарплата</label>
                                    <input id="salary" class="form-control{{ $errors->has('salary') ? ' is-invalid' : '' }}" name="salary" value="{{ old('salary') }}">
                                    @if ($errors->has('salary'))
                                        <span class="invalid-feedback"><strong>{{ $errors->first('salary') }}</strong></span>
                                    @endif
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="currency" class="col-form-label">Валюта</label>
                                    <select id="currency" class="form-control{{ $errors->has('currency') ? ' is-invalid' : '' }}" name="currency">
                                        <option value=""></option>
                                        @foreach ($data->currenciesList as $key => $value)
                                            <option value="{{ $key }}"{{ $key == old('currency') ? ' selected' : '' }}>
                                                {{ $value }}
                                            </option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="city" class="col-form-label required">Город</label>
                            <select id="city" class="form-control{{ $errors->has('city') ? ' is-invalid' : '' }}" name="city">
                                @foreach ($data->citiesList as $key => $value)
                                    <option value="{{ $key }}"{{ $key == old('city') ? ' selected' : '' }}>
                                        {{ $value }}
                                    </option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="description" class="col-form-label required">Описание</label>
                            <textarea id="description" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" rows="5" required>{{ old('description') }}</textarea>
                            @if ($errors->has('description'))
                                <span class="invalid-feedback"><strong>{{ $errors->first('description') }}</strong></span>
                            @endif
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Сохранить</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/vacancy/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    Редактировать вакансию {{ $vacancy->title }}
                    <a href="{{ route('vacancy.index') }}" class="close">
                        <span aria-hidden="true">&times;</span>
                    </a>
                </div>

                <div class="card-body">
                    <form method="POST" action="{{ route('vacancy.update', $vacancy) }}">
                        @csrf
                        @method('PUT')

                        <div class="form-group">
                            <label for="title" class="col-form-label required">Заголовок</label>
                            <input id="title" class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}" name="title" value="{{ old('title', $vacancy->title) }}" required>
                            @if ($errors->has('title'))
                                <span class="invalid-feedback"><strong>{{ $errors->first('title') }}</strong></span>
                            @endif
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="salary" class="col-form-label">Зарплата</label>
                                    <input id="salary" class="form-control{{ $errors->has('salary') ? ' is-invalid' : '' }}" name="salary" value="{{ old('salary', $vacancy->salary) }}">
                                    @if ($errors->has('salary'))
                                        <span class="invalid-feedback"><strong>{{ $errors->first('salary') }}</strong></span>
                                    @endif
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="currency" class="col-form-label">Валюта</label>
                                    <select id="currency" class="form-control{{ $errors->has('currency') ? ' is-invalid' : '' }}" name="currency">
                                        <option value=""></option>
                                        @foreach ($data->currenciesList as $key => $value)
                                            <option value="{{ $key }}"{{ $key == old('currency', $vacancy->currency_id) ? ' selected' : '' }}>
                                                {{ $value }}
                                            </option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="city" class="col-form-label required">Город</label>
                            <select id="city" class="form-control{{ $errors->has('city') ? ' is-invalid' : '' }}" name="city">
                                @foreach ($data->citiesList as $key => $value)
                                    <option value="{{ $key }}"{{ $key == old('city', $vacancy->city_id) ? ' selected' : '' }}>
                                        {{ $value }}
                                    </option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="description" class="col-form-label required">Описание</label>
                            <textarea id="description" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" rows="5" required>{{ old('description', $vacancy->description) }}</textarea>
                            @if ($errors->has('description'))
                                <span class="invalid-feedback"><strong>{{ $errors->first('description') }}</strong></span>
                            @endif
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Сохранить</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/vacancy/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    Вакансии
                    <a href="{{ route('home') }}" class="close">
                        <span aria-hidden="true">&times;</span>
                    </a>
                </div>

                <div class="card-body">
                    @can('manage-vacancies')
                        <p><a href="{{ route('vacancy.create') }}" class="btn btn-success">Добавить вакансию</a></p>
                    @endcan
                    <table class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>Дата</th>
                            <th>Заголовок</th>
                            <th>Город</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($vacancies as $vacancy)
                            <tr>
                                <td>{{$vacancy->created_at}}</td>
                                <td><a href="{{ route('vacancy.show', $vacancy->id) }}">{{$vacancy->title}}</a></td>
                                <td>{{$vacancy->city->title}}</td>
                                <td>
                                    @can('manage-vacancies')
                                        <div class="d-flex flex-row">
                                            <a href="{{ route('vacancy.show', $vacancy) }}" class="btn btn-sm btn-primary mr-1">Детали</a>
                                            <form method="POST" action="{{ route('vacancy.destroy', $vacancy) }}">
                                                @csrf
                                                @method('DELETE')
                                                <button class="btn btn-sm btn-danger mr-1">Удалить</button>
                                            </form>
                                        </div>
                                    @endcan
                                </td>
                            </tr>
                        @endforeach

                        </tbody>
                    </table>
                    {{ $vacancies->links() }}
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/vacancy/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <a href="{{ route('vacancy.index') }}" class="close"><span aria-hidden="true">&times;</span></a>
                    <h3>Вакансия: {{$vacancy->title}}</h3>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <p>
                                @can('manage-vacancies')
                                    <a href="{{ route('vacancy.edit', $vacancy) }}" class="btn btn-success">Редактировать</a>
                                @endcan
                            </p>
                            <table class="table table-bordered table-striped">
                                <tbody>
                                    <tr>
                                        <th>Заголовок</th><td>{{ $vacancy->title }}</td>
                                    </tr>
                                    <tr>
                                        <th>Зарплата</th><td>{{ $vacancy->salary . ' ' . ($vacancy->currency_id ? $vacancy->currency->title : '') }}</td>
                                    </tr>
                                    <tr>
                                        <th>Город</th><td>{{ $vacancy->city_id ? $vacancy->city->title : ''}}</td>
                                    </tr>
                                    <tr>
                                        <th>Описание</th><td>{{ $vacancy->description }}</td>
                                    </tr>
                                    <tr>
                                        <th>Добавил</th><td>{{ $vacancy->user->first_name . ' ' . $vacancy->user->last_name }}</td>
                                    </tr>
                                    <tr>
                                        <th>Добавлено</th><td>{{ $vacancy->created_at }}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection