routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::group([
    'middleware' => ['auth', 'can:use-site'],
], function () {

/**
 * HOME &EVENT
 */
Route::get('/', 'HomeController@index')->name('home');
Route::get('/candidates', 'Candidate\CandidateController@getListMatch');
Route::get('/candidates-for-interview', 'Candidate\CandidateController@getCandidatesForInterview');
    Route::get('candidate/stat','Candidate\CandidateController@stat')->name('candidate.stat');

Route::resource('candidate', 'Candidate\CandidateController');
Route::group([
        'prefix' => 'candidate',
        'as' => 'candidate.',
        'namespace' => 'Candidate',
    ],
    function () {

        Route::post('change-status/{candidate}/{status}', 'CandidateController@changeStatus')->name('changeStatus');
        Route::get('create-candidate-record/{user}', 'CandidateController@createCandidateRecord')->name('createCandidateRecord');
        Route::post('store-candidate-record/{user}', 'CandidateController@storeCandidateRecord')->name('storeCandidateRecord');
        Route::get('get', 'CandidateController@getList');
        Route::get('candidates', 'CandidateController@getListMatch');
    }
);

Route::resource('user', 'User\UserController');
Route::group([
    'prefix' => 'user',
    'as' => 'user.',
    'namespace' => 'User',
],
    function () {
        Route::post('change-status/{user}/{status}', 'UserController@changeStatus')->name('changeStatus');
    }
);

Route::resource('vacancy', 'VacancyController');

Route::group([
    'prefix' => 'data',
    'as' => 'data.',
    'namespace' => 'Data',
],
    function () {
        Route::resource('currency', 'CurrencyController');
        Route::resource('city', 'CityController');
        Route::resource('position', 'PositionController');
        Route::resource('company', 'CompanyController');
        Route::resource('remote-access', 'RemoteAccessController');
    }
);

/**
 * INTERVIEWS
 */
Route::resource('interview', 'InterviewController');
Route::get('interview/candidates/all', 'InterviewController@getCandidates')->name('interview.candidates.getAll');


/**
 * EVENTS & CALENDAR
 */
Route::any('calendar', 'Event\EventController@index')->name('calendar.index');
Route::any('calendar/create', 'Event\EventController@create')->name('calendar.create');
Route::any('calendar/add', 'Event\EventController@add')->name('calendar.add');

});



/**
 * USERS
 */

app/Http/Controllers/User/UserController.php
<?php
namespace App\Http\Controllers\User;

use App\Entities\Candidate;
use App\Entities\User;
use App\Http\Controllers\Controller;
use App\Http\Requests\User\CreateRequest;
use App\Http\Requests\User\UpdateRequest;
use App\Services\User\UserService;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;

/**
 * Class UserController
 */
class UserController extends Controller
{
    /**
     * @var UserService
     */
    private $service;

    /**
     * UserController constructor.
     * @param UserService $service
     */
    public function __construct(UserService $service)
    {
        $this->service = $service;
        $this->middleware('can:manage-users')->only(['changeStatus', 'destroy']);
    }

    /**
     * @return View
     */
    public function index(Request $request): View
    {
        if($request->query('fired') == 'true') {
            $users = User::firedStatus();
        }else {
            $users = User::workersStatus();
        }
        if($request->query('employer_search') != null) {
            $users->searchUser($request->query('employer_search'));
        }
        $users = $users->orderBy('last_name', 'asc')
            ->paginate(10);

        $statusesList = User::statusesList();

        return view('user.index',compact('users', 'statusesList'));
    }

    /**
     * @return View
     */
    public function create(): View
    {
        return view('user.create');
    }

    /**
     * @param CreateRequest $request
     * @return RedirectResponse
     */
    public function store(CreateRequest $request)
    {
        try {
            $this->service->createUser($request);
        } catch (\Exception $e) {
            return back()->with('error', $e->getMessage());
        }
        return redirect()->route('user.index');
    }

    /**
     * @param User $user
     * @return View
     */
    public function edit(User $user): View
    {
        $this->checkAccess($user);
        return view('user.edit', compact('user'));
    }

    /**
     * @param UpdateRequest $request
     * @param User $user
     * @return RedirectResponse
     */
    public function update(UpdateRequest $request, User $user): RedirectResponse
    {
        $this->checkAccess($user);
        $this->service->updateUserInfo($request, $user);
        return redirect()->route('user.show', $user);
    }

    /**
     * @param User $user
     * @param int $status
     * @return RedirectResponse
     */
    public function changeStatus(User $user, int $status): RedirectResponse
    {
        try {
            $this->service->changeStatus($user, $status);
        } catch (\DomainException $e) {
            return back()->with('error', $e->getMessage());
        }
        return redirect()->route('user.show', $user->id);
    }

    /**
     * @param User $user
     * @return View
     */
    public function show(User $user): View
    {
        $statusesList = Candidate::statusesList();
        $userStatusesList = User::statusesList();
        return view('user.show', compact('user', 'statusesList', 'userStatusesList'));
    }

    /**
     * @param User $user
     * @return RedirectResponse
     * @throws \Exception
     */
    public function destroy(User $user): RedirectResponse
    {
        $user->delete();
        return redirect()->back();
    }

    /**
     * @param User $user
     */
    public function checkAccess(User $user): void
    {
        if (!Gate::allows('edit-user-data', $user)) {
            abort(403);
        }
    }


}

resources/views/user/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    Создание нового кандидата
                    <a href="{{ route('user.index') }}" class="close">
                        <span aria-hidden="true">&times;</span>
                    </a>
                </div>

                <div class="card-body">
                    <form method="POST" action="{{ route('user.store') }}" enctype="multipart/form-data">
                        @csrf

                        @include('user._user-create-form-fields')

                        <div class="form-group">
                            <label class="col-form-label">Нотификации через</label>
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" name="notify_with[]" value="email" id="notify-email">
                                <label class="form-check-label" for="notify-email">
                                    Имейл
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" name="notify_with[]" value="slack" id="notify-slack">
                                <label class="form-check-label" for="notify-slack">
                                    Слак
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" name="notify_with[]" value="telegram" id="notify-telegram">
                                <label class="form-check-label" for="notify-telegram">
                                    Телеграм
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" name="notify_with[]" value="skype" id="notify-skype">
                                <label class="form-check-label" for="notify-skype">
                                    Скайп
                                </label>
                            </div>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Сохранить</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/user/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header form-inline">
                    Сотрудники
                    <a href="#" class="btn dropdown-toggle" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false"
                    >
                        <i class="fa fa-fw fa-wrench"></i>
                        Фильтр сотрудников
                    </a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <a class="dropdown-item {{request()->query('fired') != "true" ? 'active': '' }}"
                           href="{{request()->fullUrlWithQuery(['fired' => "false"])}}"
                        >Действующие</a>
                        <a class="dropdown-item {{request()->query('fired') == "true" ? 'active': '' }}"
                           href="{{request()->fullUrlWithQuery(['fired' => "true"])}}"
                        >Уволеные</a>
                    </div>
                    <form action="{{request()->fullUrl()}}" method="GET" >
                        <input type="text" name="employer_search"
                               value="{{request()->query('employer_search')!=null ? request()->query('employer_search'): ''}}"
                        >
                        @if(request()->query('fired') == "true")
                            <input type='hidden' name='fired' value='true'/>
                        @endif
                        <button type="submit"><i class="fas fa-search"></i></button>
                    </form>
                    <a href="{{ route('home') }}" class="close" style="margin-left: 55%;">
                        <span aria-hidden="true">&times;</span>
                    </a>
                </div>

                <div class="card-body">
                    @can('manage-users')
                        <p><a href="{{ route('user.create') }}" class="btn btn-success">Добавить сотрудника</a></p>
                    @endcan
                    <table class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            @if(request()->query('fired') == "true")
                            <th>Дата увольнения</th>
                            @else
                            <th>Дата принятия</th>
                            @endif
                            <th>Имя</th>
                            <th>E-mail</th>
                            <th>Статус</th>
                            <th>Фото</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($users as $user)
                            <tr>
                                @if(request()->query('fired') == "true")
                                    <td>{{$user->fired_at ? date('d.m.Y H:i', strtotime( $user->fired_at)) : ''}}</td>
                                @else
                                    <td>{{$user->employer_at ? date('d.m.Y H:i', strtotime( $user->employer_at)) : ''}}</td>
                                @endif
                                <td><a href="{{ route('user.show', $user->id) }}">{{$user->last_name . ' ' . $user->first_name . ' ' . $user->second_name}}</a></td>
                                <td>{{$user->email}}</td>
                                <td><span class="badge badge-primary">{{$statusesList[$user->status]}}</span></td>
                                <td>
                                    @if($user->photo)
                                        <img class="little-photo" src="{{ asset('storage/' . $user->photo) }}" />
                                    @endif
                                </td>
                                <td>
                                    @can('manage-users')
                                        <div class="d-flex flex-row">
                                            <a href="{{ route('user.show', $user) }}" class="btn btn-sm btn-primary mr-1">Детали</a>
                                            <form method="POST" action="{{ route('user.destroy', $user) }}">
                                                @csrf
                                                @method('DELETE')
                                                <button class="btn btn-sm btn-danger mr-1">Удалить</button>
                                            </form>
                                        </div>
                                    @endcan
                                </td>
                            </tr>
                        @endforeach

                        </tbody>
                    </table>
                    {{ $users->appends(request()->query())->links() }}
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/user/show.blade.php
<?php use App\Entities\Candidate; ?>

@extends('layouts.app')

@section('content')
<div class="row justify-content-center">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                @if($user->isCandidate())
                    <a href="{{ route('candidate.index') }}" class="close">
                        <span aria-hidden="true">&times;</span>
                    </a>
                @else
                    <a href="{{ route('user.index') }}" class="close">
                        <span aria-hidden="true">&times;</span>
                    </a>
                @endif
                <h3>
                    {{ $userStatusesList[$user->status] }}
                    {{$user->first_name . ' ' . $user->last_name}}
                </h3>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="@if ($user->isCandidate()) {{ 'col-md-5' }} @else {{ 'col-md-12' }} @endif">
                        <h4>Основные данные</h4>
                        <p>
                            @can('manage-users')
                                <div class="btn-group">
                                    <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Изменить статус пользователя
                                    </button>
                                    <div class="dropdown-menu">
                                        @foreach ($userStatusesList as $key => $value)
                                            @if ($user->status !== $key)
                                                <form method="POST" action="{{ route('user.changeStatus', ['user' => $user, 'status' => $key]) }}" class="mr-1">
                                                    @csrf
                                                    <button class="dropdown-item">{{ $value }}</button>
                                                </form>
                                            @endif
                                        @endforeach
                                    </div>
                                </div>
                            @endcan
                            @if (Gate::allows('edit-user-data', $user))
                                <a href="{{ route('user.edit', $user) }}" class="btn btn-success">Редактировать</a>
                            @endif
                        <p></p>
                        <table class="table table-bordered table-striped">
                            <tbody>
                                <tr>
                                    <th>Полное имя</th><td>{{ $user->first_name  . ' ' . $user->second_name . ' ' . $user->last_name }}</td>
                                </tr>
                                <tr>
                                    <th>Статус</th><td><span class="badge badge-{{Candidate::getBadgeColor($userStatusesList[$user->status])}}">{{ $userStatusesList[$user->status] }}</span></td>
                                </tr>
                                <tr>
                                    <th>Email</th><td>{{ $user->email }}</td>
                                </tr>
                                <tr>
                                    <th>Ссылки на соцсети</th><td>{{ $user->socials }}</td>
                                </tr>
                                <tr>
                                    <th>Образование</th><td>{{ $user->education }}</td>
                                </tr>
                                <tr>
                                    <th>Сотрудник от</th><td>{{ $user->employer_at ? date('d.m.Y H:i', strtotime( $user->employer_at)) : ''}}</td>
                                </tr>
                                <tr>
                                    @if($user->fired_at != null)
                                        <th>Уволен от</th><td>{{ $user->fired_at ? date('d.m.Y H:i', strtotime( $user->fired_at)) : ''}}</td>
                                    @endif
                                </tr>
                                <tr>
                                    <th>Фото</th>
                                    <td>
                                        @if ($user->photo)
                                            <img class="little-photo" src="{{ asset('storage/' . $user->photo) }}" />
                                        @endif
                                    </td>
                                </tr>
                            <tr>
                                <th>Телефон</th><td>{{ $user->phone }}</td>
                            </tr>
                            <tr>
                                <th>Skype</th>
                                <td>
                                    {{ $user->skype }}
                                    @if( !empty( env('INTERVIEW_NOTIFICATOR_SKYPE_BOT_ADD_URL') ) )
                                        <a target="_blank" href="{{env('INTERVIEW_NOTIFICATOR_SKYPE_BOT_ADD_URL')}}">Добавить Бота</a>
                                    @endif
                                </td>

                            </tr>
                            <tr>
                                <th>Телеграм</th>
                                <td>
                                    {{ $user->telegram }}
                                    @if( !empty( env('INTERVIEW_NOTIFICATOR_TELEGRAM_BOT') ) )
                                        Bot ({{env('INTERVIEW_NOTIFICATOR_TELEGRAM_BOT')}})
                                    @endif
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                    @if ($user->isCandidate())
                        <div class="col-md-7">
                            <h4>История кандидатства</h4>
                            @can('manage-users')
                                <p><a href="{{ route('candidate.createCandidateRecord', $user) }}" class="btn btn-success">Добавить</a></p>
                            @endcan
                            <div class="accordion" id="accordionHistory">
                                @php($first = true)
                                @foreach ($user->candidatesHistory as $candidate)
                                <div class="card">
                                    <div class="card-header" id="{{ $candidate->id }}">
                                        <h5 class="mb-1">
                                            <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapse{{ $candidate->id }}" aria-expanded="true" aria-controls="collapse{{ $candidate->id }}">
                                                {{ $candidate->created_at }}
                                            </button>
                                        </h5>
                                    </div>

                                    <div id="collapse{{ $candidate->id }}" class="collapse @if ($first) show @endif" aria-labelledby="{{ $candidate->id }}" data-parent="#accordionHistory">
                                        <div class="card-body">
                                            @if ($first)
                                                @can('manage-users')
                                                    <div class="btn-group">
                                                        <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                            Изменить статус кандидата
                                                        </button>
                                                        <div class="dropdown-menu">
                                                            @foreach ($statusesList as $key => $value)
                                                                @if ($candidate->status !== $key)
                                                                    <form method="POST" action="{{ route('candidate.changeStatus', ['candidate' => $candidate, 'status' => $key]) }}" class="mr-1">
                                                                        @csrf
                                                                        <button class="dropdown-item">{{ $value }}</button>
                                                                    </form>
                                                                @endif
                                                            @endforeach
                                                        </div>
                                                    </div>
                                                    <a href="{{ route('candidate.edit', $candidate) }}" class="btn btn-success">Редактировать</a>
                                                @endcan
                                            @endif
                                            <table class="table table-bordered table-striped">
                                                <tbody>
                                                    <tr>
                                                        <th>Статус</th><td><span class="badge badge-{{\App\Entities\Candidate::getBadgeColor($statusesList[$candidate->status])}}">{{ $statusesList[$candidate->status] }}</span></td>
                                                    </tr>
                                                    <tr>
                                                        <th>Рекрутер</th><td>{{ $candidate->recruiter->last_name . ' ' . $candidate->recruiter->first_name }}</td>
                                                    </tr>
                                                    <tr>
                                                        <th>Должность</th><td>{{ $candidate->position_id ? $candidate->position->title : ''}}</td>
                                                    </tr>
                                                    <tr>
                                                        <th>Зарплата</th><td>{{ $candidate->salary . ' ' . $candidate->currency->title }}</td>
                                                    </tr>
                                                    <tr>
                                                        <th>Город</th><td>{{ $candidate->city->title }}</td>
                                                    </tr>
                                                    <tr>
                                                        <th>Ссылка на резюме</th><td>{{ $candidate->cv_src }}</td>
                                                    </tr>
                                                    <tr>
                                                        <th>Файл резюме</th>
                                                        <td>
                                                            @if ($candidate->cv_file)
                                                                <a target="_blank" href="{{ asset('storage/' . $candidate->cv_file) }}">скачать</a>
                                                            @endif
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <th>Языки</th><td>{{ $candidate->languages }}</td>
                                                    </tr>
                                                    <tr>
                                                        <th>Описание</th><td>{{ $candidate->description }}</td>
                                                    </tr>
                                                    <tr>
                                                        <th>Последняя компания</th><td>{{ $candidate->last_company_id ? $candidate->lastCompany->title : ''}}</td>
                                                    </tr>
                                                    <tr>
                                                        <th>Заметки</th><td>{{ $candidate->notes }}</td>
                                                    </tr>
                                                    <tr>
                                                        <th>Дата добавления</th><td>{{ $candidate->created_at }}</td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                @php($first = false)
                                @endforeach
                            </div>
                        </div>
                    @endif
                </div>

            </div>
        </div>
    </div>
</div>
@endsection