routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::group([
    'middleware' => ['auth', 'can:use-site'],
], function () {

/**
 * HOME &EVENT
 */
Route::get('/', 'HomeController@index')->name('home');
Route::get('/candidates', 'Candidate\CandidateController@getListMatch');
Route::get('/candidates-for-interview', 'Candidate\CandidateController@getCandidatesForInterview');
    Route::get('candidate/stat','Candidate\CandidateController@stat')->name('candidate.stat');

Route::resource('candidate', 'Candidate\CandidateController');
Route::group([
        'prefix' => 'candidate',
        'as' => 'candidate.',
        'namespace' => 'Candidate',
    ],
    function () {

        Route::post('change-status/{candidate}/{status}', 'CandidateController@changeStatus')->name('changeStatus');
        Route::get('create-candidate-record/{user}', 'CandidateController@createCandidateRecord')->name('createCandidateRecord');
        Route::post('store-candidate-record/{user}', 'CandidateController@storeCandidateRecord')->name('storeCandidateRecord');
        Route::get('get', 'CandidateController@getList');
        Route::get('candidates', 'CandidateController@getListMatch');
    }
);

Route::resource('user', 'User\UserController');
Route::group([
    'prefix' => 'user',
    'as' => 'user.',
    'namespace' => 'User',
],
    function () {
        Route::post('change-status/{user}/{status}', 'UserController@changeStatus')->name('changeStatus');
    }
);

Route::resource('vacancy', 'VacancyController');

Route::group([
    'prefix' => 'data',
    'as' => 'data.',
    'namespace' => 'Data',
],
    function () {
        Route::resource('currency', 'CurrencyController');
        Route::resource('city', 'CityController');
        Route::resource('position', 'PositionController');
        Route::resource('company', 'CompanyController');
        Route::resource('remote-access', 'RemoteAccessController');
    }
);

/**
 * INTERVIEWS
 */
Route::resource('interview', 'InterviewController');
Route::get('interview/candidates/all', 'InterviewController@getCandidates')->name('interview.candidates.getAll');


/**
 * EVENTS & CALENDAR
 */
Route::any('calendar', 'Event\EventController@index')->name('calendar.index');
Route::any('calendar/create', 'Event\EventController@create')->name('calendar.create');
Route::any('calendar/add', 'Event\EventController@add')->name('calendar.add');

});



/**
 * USERS
 */

app/Http/Controllers/InterviewController.php
<?php

namespace App\Http\Controllers;

use App\Debug;
use App\Entities\Candidate;
use App\Entities\Data\City;
use App\Entities\Data\DataDTO;
use App\Entities\Data\Position;
use App\Entities\Data\Vacancy;
use App\Entities\User;
use App\Entities\Data\Organizer;
use App\Http\Requests\Interview\InterviewRequest;
use App\Http\Requests\Interview\UpdateRequest;
use App\Interview;
use App\InterviewEmployee;
use App\Services\Interview\InterviewService;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\View\View;

class InterviewController extends Controller
{
    /**
     * @var InterviewService
     */
    private $service;

    /**
     * InterviewController constructor.
     * @param InterviewService $service
     */
    public function __construct(InterviewService $service)
    {
        $this->service = $service;
        $this->middleware('can:manage-users')->except(['index']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $interviews = Interview::orderBy('date_from', 'asc')->paginate(5);

        $usersIds = $interviews->pluck("candidate_id");
        $users = User::whereIn('id', $usersIds)->get()->keyBy("id");

        $positionsIDs = $interviews->pluck("position_id")->unique()->filter();
        $positions = Position::whereIn('id', $positionsIDs)->get()->keyBy("id");

        $vacanciesIDs = $interviews->pluck("vacancy_id")->unique()->filter();
        $vacancies = Vacancy::whereIn('id', $vacanciesIDs)->get()->toArray();

        $citiesIDs = $interviews->pluck("city_id")->unique()->filter();
        $cities = City::whereIn('id', $citiesIDs)->get()->keyBy("id");

        return view('interview.index', compact('candidates', 'interviews', 'interview_query',
        'users', 'positions', 'vacancies', 'cities', 'positions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = new DataDTO();
        return view('interview.create', compact('data'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $this->service->createInterview($request);
        } catch (\Exception $e) {
            return back()->with('error', $e->getMessage());
        }
        return redirect()->route('interview.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Interview $interview): View
    {
        $interview_id = (int)$interview->id;

        $interview = Interview::with(['user' => function ($query) use ($interview_id) {

            }])
            ->where('id', $interview_id)
            ->with('interviewEmployee')
//            ->with('user')
            ->get();

//        Debug::all($interview[0]['user']);

        return \view('interview.show', compact('interview', 'interview_id'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Interview $interview): View
    {
        $interview_id = (int)$interview->id;
        $interview = Interview::with(['user' => function(){

        }])
            ->with('candidate')
            ->with('city')
            ->with('position')
            ->with('vacancy')
            ->with('interviewEmployee')
            ->where('id', $interview_id)
            ->get();

        $interview = $interview[0];
        $data = new DataDTO();

        $allInterviewersIDArray = InterviewEmployee::all()                              // get all the data
            ->where('interview_id', $interview_id)
            ->toArray();
        $allInterviewersIDArray = array_pluck($allInterviewersIDArray, 'user_id'); // get just purified `user_id` [0=>1, 1=>3, 2=>7]

        return view('interview.edit', compact('data', 'interview_id', 'interview', 'allInterviewersIDArray'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRequest $request, Interview $interview)
    {
        try {
            $interview->update($request->all());
        } catch (\Exception $e) {
            return back()->with('error', $e->getMessage());
        }

        //change related entry in `organizer` table
        try {
            DB::table('organizer')
                ->where('interview_id', '=', $request->only('interview_id'))
                ->update(
                    [
                        'start' => $interview->date_from,
                        'end' => $interview->date_from
                    ]);

        } catch (\Exception $e) {
            return back()->with('error', $e->getMessage());
        }

        return redirect()->route('interview.show', $interview);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Interview $interview): RedirectResponse
    {
        $interview->delete();
        return redirect()->back();
    }

    public function remove($id)
    {

    }

    public function getCandidates()
    {
        $data = new DataDTO();
        return $data->candidatesList;
    }
}

resources/views/interview/_interview-edit-form-fields.blade.php
{{--@dd($interview)--}}

<div class="form-group">
    <input type="hidden" value="{{$interview->id}}" name="interview_id">
    <label for="exampleFormControlSelect1">Кандидат</label>
    <select id="candidate" class="form-control{{ $errors->has('candidate_id') ? ' is-invalid' : '' }}" name="candidate_id">
        <option value="{{$interview->user->id}}">{{$interview->user->first_name}} {{$interview->user->last_name}}</option>

        {{--{{ $i = 0 }}
        @foreach ($data->candidatesList as $key => $value)
            <option value="{{ $data->candidatesList[$i]->user->id }}"{{ $key == old('position') ? ' selected' : '' }}>
                {{ $data->candidatesList[$i]->user->first_name }}
                {{ $data->candidatesList[$i]->user->second_name }}
                {{ $data->candidatesList[$i]->user->last_name }}
                &nbsp;&nbsp;
                ({{ $data->candidatesList[$i]->city->title }},&nbsp;
                {{ $data->candidatesList[$i]->position->title }})
            </option>
            {{ $i++ }}
        @endforeach--}}

    </select>
    @if ($errors->has('candidate_id'))
        <span class="invalid-feedback"><strong>{{ $errors->first('candidate_id') }}</strong></span>
    @endif
</div>
<div class="form-group">
    <label for="exampleFormControlSelect1">Позиция</label>
    <select id="position" class="form-control{{ $errors->has('position_id') ? ' is-invalid' : '' }}" name="position_id">
        @foreach ($data->positionsList as $key => $value)
            <option value="{{ $key }}"{{ $key == $interview->position_id ? ' selected' : '' }}>
                {{ $value }}
            </option>
        @endforeach
    </select>
    @if ($errors->has('position_id'))
        <span class="invalid-feedback"><strong>{{ $errors->first('position_id') }}</strong></span>
    @endif
</div>
<div class="form-group">
    <label for="exampleFormControlSelect1">Город</label>
    <select  id="city_id" name="city_id" class="form-control{{ $errors->has('city_id') ? ' is-invalid' : '' }}">
        @foreach ($data->citiesList as $key => $value)
            <option value="{{ $key }}"{{ $key == $interview->city_id ? ' selected' : '' }}>
                {{ $value }}
            </option>
        @endforeach
    </select>
    @if ($errors->has('city_id'))
        <span class="invalid-feedback"><strong>{{ $errors->first('city_id') }}</strong></span>
    @endif
</div>
<div class="form-group">
    <label for="exampleFormControlSelect1">Вакансия</label>
    <select id="vacancy_id" name="vacancy_id" class="form-control{{ $errors->has('vacancy_id') ? ' is-invalid' : '' }}" name="vacancy_id">
        <option value="{{$interview->vacancy[0]->id}}">{{$interview->vacancy[0]->title}}</option>
        @foreach ($data->vacanciesList as $key => $value)
            <option value="{{ $key }}"{{ $key == old('position') ? ' selected' : '' }}>
                {{ $value }}
            </option>
        @endforeach
    </select>
    @if ($errors->has('vacancy_id'))
        <span class="invalid-feedback"><strong>{{ $errors->first('vacancy_id') }}</strong></span>
    @endif
</div>

<div class="form-group">
    <label for="exampleFormControlSelect2">Наши участники интервью</label>
    <br>

{{--@dd($allInterviewersIDArray);--}}

    @for ($j = 0; $j < count($data->usersHRList); $j++)
<!--        --><?php //echo in_array($data->usersHRList[$j]->id, $allInterviewersIDArray) ?  ' checked' : '' ?>
        <input type="checkbox"
               data-user_id="{{ $data->usersHRList[$j]->id }}"
               data-intreviewer_id="{{ $interview->interviewEmployee[$j]->user_id ?? ''}}"
               {{in_array($data->usersHRList[$j]->id, $allInterviewersIDArray) ?  ' checked' : ''}}
        > &nbsp;
            {{ $data->usersHRList[$j]->first_name  }}
            {{ $data->usersHRList[$j]->last_name }}

        <br>
    @endfor
<br>
{{--@endfor--}}
</div>
<div class="form-group">
    <label for="calendar_event_begin">Дата интервью</label>
    <div class='input-group date' id='begin-datetimepicker' data-target-input="nearest">
        @if ($errors->has('start'))
            <div class="alert alert-danger">{{ $errors->first('start') }}</div>
        @endif
        <input type="text" class="form-control datetimepicker-input" data-target="#begin-datetimepicker" value="{{date('d.m.Y H:i', strtotime($interview->date_from))}}">
        <div class="input-group-append" data-target="#begin-datetimepicker" data-toggle="datetimepicker">
            <div class="input-group-text"><i class="far fa-calendar-alt"></i></div>
        </div>
    </div>
    <input type="hidden" name="date_from" class="form-control" id="calendar_event_begin" value="{{date('Y-m-d H:i:s', strtotime($interview->date_from))}}">
</div>

{{--<div class="row">--}}
{{--<div class="col">--}}
    {{--<label for="date">Дата интервью</label>--}}
    {{--<input id="date" type="date" class="form-control" name="date_from" value="{{$interview->date_from}}" placeholder="Изменяемая дата: {{$interview->date_from}}">--}}
{{--</div>--}}
{{--<div class="col">--}}
    {{--<label for="time_begin">Время начала</label>--}}
    {{--<input id="time" type="text" class="form-control" name="date_to" value="{{$interview->date_to}}">--}}
{{--</div>--}}
{{--</div>--}}

{{--<h3>Inline</h3>
<div id="date_picker"> </div>
<script type="text/javascript">
$(function(){
    $('#date_picker').dtpicker();
});
</script>--}}
<script>
    $(function () {
        $('#begin-datetimepicker').datetimepicker({
        });
        $('#begin-datetimepicker').on('change.datetimepicker', function (e) {
            $('input#calendar_event_begin').val(window.moment(e.date).format('YYYY-MM-DD HH:mm:ss'));
        });


    });
</script>

resources/views/interview/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    Создание нового интервью
                    <a href="{{ route('interview.index') }}" class="close">
                        <span aria-hidden="true">&times;</span>
                    </a>
                </div>
                <div class="card-body">
                    <form method="POST" action="{{ route('interview.store') }}" enctype="multipart/form-data">
                        @csrf

                        @include('interview._interview-create-form-fields')

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Сохранить</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/interview/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    Редактирование интервью
                    <a href="{{ route('interview.index') }}" class="close">
                        <span aria-hidden="true">&times;</span>
                    </a>
                </div>
                <div class="card-body">
                    <form method="post" action="{{ route('interview.update', $interview) }}" enctype="multipart/form-data">
                        <input name="_method" type="hidden" value="PUT">
                        @csrf

                        @include('interview._interview-edit-form-fields')

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Сохранить</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

@endsection

resources/views/interview/index.blade.php
@extends('layouts.app')

@section('content')

<div class="row justify-content-center">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                Предстоящие интервью
                <a href="{{ route('home') }}" class="close">
                    <span aria-hidden="true">&times;</span>
                </a>
            </div>

            <div class="card-body">
                @can('manage-users')
                    <p><a href="{{ route('interview.create') }}" class="btn btn-success">Добавить новое</a></p>
                @endcan
                <table class="table table-bordered table-striped">
                    <thead>
                    <tr>
                        <th>ФИО</th>
                        <th>Фото</th>
                        <th>Позиция</th>
                        <th>Город</th>
                        <th>Дата</th>
                        <th>Время</th>
                        <th>Опции</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?//php echo date('d-m-Y', time()) ?>
                    @foreach ($interviews as $interview)
                        <?php $today = $interview['date_from'] === date('Y-m-d') ?>
                        <tr></tr>
                        <tr style="{{ $today ? 'background:#F9E8E8' : 'background:white'  }}">
                            <td>
                                <a href="{{ route('user.show', $users[$interview['candidate_id']]['id']) }}">
                                    {{$users[$interview['candidate_id']]['first_name'] or 'FIRST_NAME_IS_NOT_DEFINED'}}
                                    {{$users[$interview['candidate_id']]['second_name'] or 'SECOND_NAME_IS_NOT_DEFINED' }}
                                    {{$users[$interview['candidate_id']]['last_name'] or 'LAST_NAME_IS_NOT_DEFINED' }}
                                </a>
                                <br>
                                <span style="font-size: 12px">{{ $users[$interview['candidate_id']]['phone'] or 'Phone is not set' }}</span>
                            </td>
                            <td>
                                <img src="storage/{{$users[$interview['candidate_id']]['photo'] or 'Photo is not set'}}" class="img rounded-circle" width="60px" alt="Photo is not set"/>
                            </td>
                            <td>
                                {{$positions[$interview['position_id']]['title'] or 'POSITION_IS_NOT_DEFINED'}}
                                <br> <span style="font-size: 10px">Присутствуют:</span>

                                @foreach($interview->interviewEmployee as $interviewEmployee)
                                    <span class="badge badge-pill badge-light">
                                        <i class="fas fa-times interviewer-remove interviewer-{{$interviewEmployee->user_id or 'USER_ID_IS_NOT_DEFINED'}}" style="cursor:pointer;" data-interviewer_id="{{$interviewEmployee->user_id or 'USER_ID_IS_NOT_DEFINED'}}"></i>
                                            {{ \App\Entities\User::getUserById($interviewEmployee->user_id) ?? '' }}
                                    </span>
                                @endforeach
                            </td>
                            <td>{{$cities[$interview['city_id']]['title'] or 'CITY_IS_NOT_DEFINED'}}</td>
                            <td>{{date('d.m.Y', strtotime($interview->date_from))}} <br>
                                <?php echo $today ? '<span class="badge badge-danger">СЕГОДНЯ</span>' : '' ?>
                            </td>
                            <td>
                                {{date('H:i', strtotime($interview->date_from))}}
                                <?php $left = (int)(((strtotime($interview->date_from) - time())) / 60) ?>
                                <!-- +3 часа к нашей зоне -->
                                    @if($left < 60 && $left > 0)
                                        <i style="color:red" class="fa fa-bell" aria-hidden="true"></i>
                                        <span class="badge badge-pill badge-success">Через {{ $left }} мин</span>
                                    @elseif($left < 15 && $left > 0)
                                        <br>
                                        <span class="badge badge-pill badge-success">Через {{ $left }} мин</span>
                                    @elseif($left > -30 && $left <= 0)
                                        <br>
                                        <span class="badge badge-pill badge-danger">Идёт собеседование</span>
                                    @elseif($left <= -30)
                                        <br>
                                        <span class="badge badge-pill badge-secondary">Cобеседование прошло</span>
                                    @endif
                            </td>
                            <td>
                                @can('manage-users')
                                    <div class="d-flex flex-row">
                                        <a href="{{ route('interview.show', $interview ?? '') }}" class="btn btn-sm btn-primary mr-1">Детали</a>
                                        <form method="POST" action="{{ route('interview.destroy', $interview ?? '') }}">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn btn-sm btn-danger mr-1">Удалить</button>
                                        </form>
                                    </div>
                                @endcan
                            </td>
                            {{--<td><span class="badge badge-primary">{{$statusesList[$user->status]}}</span></td>
                            <td>
                                @if($user->photo)
                                    <img class="little-photo" src="{{ asset('storage/' . $user->photo) }}" />
                                @endif
                            </td>
                            <td>
                                @can('manage-users')
                                    <div class="d-flex flex-row">
                                        <a href="{{ route('user.show', $user) }}" class="btn btn-sm btn-primary mr-1">Детали</a>
                                        <form method="POST" action="{{ route('user.destroy', $user) }}">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn btn-sm btn-danger mr-1">Удалить</button>
                                        </form>
                                    </div>
                                @endcan
                            </td>--}}
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                {{ $interviews->links() }}
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/interview/show.blade.php
@extends('layouts.app')

@section('content')

    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    {{--@if($user->isCandidate())--}}
                        <a href="{{ route('candidate.index') }}" class="close">
                            {{--@else--}}
                                <a href="{{ route('user.index') }}" class="close">
                                    {{--@endif--}}
                                    <span aria-hidden="true">&times;</span>
                                </a>
                        </a>
                                <h3>
{{--                                    {{ $userStatusesList[$user->status] }}--}}
{{--                                    {{$user->first_name . ' ' . $user->last_name}}--}}
                                </h3>
                </div>
                <div class="card-body">
                    <div class="row">
{{--                        <div class="@if ($user->isCandidate()) {{ 'col-md-5' }} @else {{ 'col-md-12' }} @endif">--}}
                            <h4>Основные данные</h4>
                        <p></p>
                            @can('manage-users')
                                <div class="btn-group">
                                    {{--<button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Изменить статус пользователя
                                    </button>
                                    <div class="dropdown-menu">
                                        @foreach ($userStatusesList as $key => $value)
                                            @if ($user->status !== $key)
                                                <form method="POST" action="{{ route('user.changeStatus', ['user' => $user, 'status' => $key]) }}" class="mr-1">
                                                    @csrf
                                                    <button class="dropdown-item">{{ $value }}</button>
                                                </form>
                                            @endif
                                        @endforeach
                                    </div>--}}
                                   {{-- <button type="button" class="btn btn-danger" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="margin-left: 30px; margin-bottom: 5px">
                                        Редактировать интервью
                                    </button>--}}
                                </div>
                            @endcan
                            {{--@if (Gate::allows('edit-user-data', $user))--}}
                                <a href="{{ route('interview.edit', $interview_id) }}" class="btn btn-danger" style="margin-bottom: 5px; margin-left: 30px;">Редактировать</a>
                                {{--@endif--}}
                                </p>
                                <table class="table table-bordered table-striped">
                                    <tbody>
                                    <tr>
                                        <th>Полное имя</th><td>{{ $interview[0]->user->first_name . ' ' . $interview[0]->user->last_name . ' ' . $interview[0]->user->second_name }}</td>
                                    </tr>
                                    <tr>
                                        <th>Город</th><td>{{ $interview[0]->city->title }}</td>
                                    </tr>
                                    <tr>
                                        <th>Должность</th><td>{{ $interview[0]->position->title }}</td>
                                    </tr>
                                    <tr>
                                        <th>Вакансия</th><td>{{ $interview[0]->vacancy[0]->title }}</td>
                                    </tr>
                                    <tr>
                                        <th>Участники от нас</th>
                                        <td>
                                            @foreach($interview[0]->interviewEmployee as $interviewEmployee)
                                                {{$interviewEmployee}}
                                            @endforeach
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>Телефон</th><td>{{ $interview[0]->user->phone }}</td>
                                    </tr>
                                    <tr>
                                        <th>E-mail</th><td>{{ $interview[0]->user->email }}</td>
                                    </tr>
                                    <tr>
                                        <th>Ссылки на соцсети</th><td>{{ $interview[0]->user->socials }}</td>
                                    </tr>
                                    <tr>
                                        <th>Дата</th><td>{{ date('d.m.Y', strtotime($interview[0]->date_from))}}</td>
                                    </tr>
                                    <tr>
                                        <th>Время</th><td>{{ date('H:i', strtotime($interview[0]->date_from))}}</td>
                                    </tr>
                                    <tr>
                                        <th>Фото</th>
                                        <td>
                                            @if ($interview[0]->user->photo)
                                                <img class="little-photo img-circle" src="{{ asset('storage/' . $interview[0]->user->photo) }}" />
                                            @endif
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

@endsection